name: SLPHOTO
favicon: null
layout_spectrum: 1
typography_spectrum: 0.57038
title: 'Your best pictures are still to come '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#8b898e'
    - '#181619'
    - '#48494d'
    - '#c4c6c3'
    - '#f3f0e1'
  brandStrength: 0.3125
  lightness: 0.4375
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
