name: SLPHOTO
favicon: null
layout_spectrum: 1
typography_spectrum: 0.57038
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010004'
    - '#498491'
    - '#2e505a'
    - '#aeb08f'
    - '#d0d3c6'
  brandStrength: 0.3125
  lightness: 0.4375
  saturation: 0.4980882201343775
  rhythmicContrast: 0.5
purpose: []
